// Instructions: Add these includes to nes-sql-parser/src/AntlrSQLQueryPlanCreator.cpp

#include <Functions/Meos/ExternBoolGeogIntersectsLogicalFunction.hpp>
#include <Functions/Meos/ExternBoolGeomContainsLogicalFunction.hpp>
#include <Functions/Meos/ExternBoolGeomIntersects2dLogicalFunction.hpp>
#include <Functions/Meos/ExternBoolGeomIntersects3dLogicalFunction.hpp>
#include <Functions/Meos/TcontainsGeoTgeoLogicalFunction.hpp>
#include <Functions/Meos/TcontainsTgeoGeoLogicalFunction.hpp>
#include <Functions/Meos/TcontainsTgeoTgeoLogicalFunction.hpp>
#include <Functions/Meos/TintersectsGeoTgeoLogicalFunction.hpp>
#include <Functions/Meos/TintersectsTgeoGeoLogicalFunction.hpp>
#include <Functions/Meos/TintersectsTgeoTgeoLogicalFunction.hpp>
#include <Functions/Meos/ExternBoolContainsSetBigintLogicalFunction.hpp>
#include <Functions/Meos/ExternBoolContainsSetDateLogicalFunction.hpp>
#include <Functions/Meos/ExternBoolContainsSetFloatLogicalFunction.hpp>
#include <Functions/Meos/ExternBoolContainsSetIntLogicalFunction.hpp>
#include <Functions/Meos/ExternBoolContainsSetSetLogicalFunction.hpp>
#include <Functions/Meos/ExternBoolContainsSetTextLogicalFunction.hpp>
#include <Functions/Meos/ExternBoolContainsSetTimestamptzLogicalFunction.hpp>
#include <Functions/Meos/ExternBoolContainsSpanBigintLogicalFunction.hpp>
#include <Functions/Meos/ExternBoolContainsSpanDateLogicalFunction.hpp>
#include <Functions/Meos/ExternBoolContainsSpanFloatLogicalFunction.hpp>
#include <Functions/Meos/ExternBoolContainsSpanIntLogicalFunction.hpp>
#include <Functions/Meos/ExternBoolContainsSpanSpanLogicalFunction.hpp>
#include <Functions/Meos/ExternBoolContainsSpanSpansetLogicalFunction.hpp>
#include <Functions/Meos/ExternBoolContainsSpanTimestamptzLogicalFunction.hpp>
#include <Functions/Meos/ExternBoolContainsSpansetBigintLogicalFunction.hpp>
#include <Functions/Meos/ExternBoolContainsSpansetDateLogicalFunction.hpp>
#include <Functions/Meos/ExternBoolContainsSpansetFloatLogicalFunction.hpp>
#include <Functions/Meos/ExternBoolContainsSpansetIntLogicalFunction.hpp>
#include <Functions/Meos/ExternBoolContainsSpansetSpanLogicalFunction.hpp>
#include <Functions/Meos/ExternBoolContainsSpansetSpansetLogicalFunction.hpp>
#include <Functions/Meos/ExternBoolContainsSpansetTimestamptzLogicalFunction.hpp>
#include <Functions/Meos/ExternBoolContainsNumspanTnumberLogicalFunction.hpp>
#include <Functions/Meos/ExternBoolContainsTboxTnumberLogicalFunction.hpp>
#include <Functions/Meos/ExternBoolContainsTemporalTstzspanLogicalFunction.hpp>
#include <Functions/Meos/ExternBoolContainsTemporalTemporalLogicalFunction.hpp>
#include <Functions/Meos/ExternBoolContainsTnumberNumspanLogicalFunction.hpp>
#include <Functions/Meos/ExternBoolContainsTnumberTboxLogicalFunction.hpp>
#include <Functions/Meos/ExternBoolContainsTnumberTnumberLogicalFunction.hpp>
#include <Functions/Meos/ExternBoolContainsTstzspanTemporalLogicalFunction.hpp>
